name: Ubuntu ARM64 Workflow
on: [push]

jobs:
  ubuntu-22-04:
    if:
    runs-on: ubuntu-22.04-arm64
    strategy:
      matrix:
        architecture: [arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run build script
        run: |
          uname -m
          uname -a
          swift -version
