name: Ubuntu ARM64 Workflow
on: [push]

jobs:
  ubuntu-22-04-arm64:
    if: contains(github.event.head_commit.message, 'linux-arm64')
    runs-on: ubuntu-22.04-arm64
    strategy:
      matrix:
        architecture: [arm64]
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v3
      - name: Run build script
        id: system-info
        run: |
          uname -m
          uname -a
          swift -version



  ubuntu22-arm64:
    # 表示git commit 中包含linux-arm64字符串时该任务才执行，否则直接跳过
    if: contains(github.event.head_commit.message, 'linux-arm64')
    # 通过actions-runner远程使用Termux-Ubuntu系统
    runs-on: ubuntu-22.04-arm64
    steps:
      - name: Checkout
        uses: checkout-code
      - name: Show Info
        uses: system-info

