name: Swift on ARM64 Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swift:5.4-focal-arm64
    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: |
        swift build
        swift test
