name: Custom GitHub Actions runner Demo 
on: [push] 
jobs: 
  Build-and-Run-FizzBuzz: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Check out repository code 
        uses: actions/checkout@v3 
      - run: uname -m


  Build-and-Run-FizzBuzz-arm:
    strategy: 
      matrix: 
        os: [ubuntu-latest, [ linux, ARM64]] 
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Check out repository code 
        uses: actions/checkout@v3 
      - run: uname -m
