name: Swift on ARM64 Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swift:5.7-focal-arm64
    steps:
    - uses: actions/checkout@v3
    - name: System Info
      run: |
        uname -a
        swift -version
